Abundance_Rm/Areas/Admin/Controllers/StaffCourseAllocationController.cs
using Abundance_Rm.Business;
using Abundance_Rm.Model.Entity;
using Abundance_Rm.Model.Model;
using Abundance_Rm.Areas.Admin.ViewModel;
using Abundance_Rm.Controllers;
using Abundance_Rm.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace Abundance_Rm.Areas.Admin.Controllers
{
    [Authorize]
    public class StaffCourseAllocationController : BaseController
    {
        private const string ID = "Id";
        private const string NAME = "Name";
        private StaffCourseAllocationViewModel viewModel;
        public ActionResult AllocatedCourses()
        {
            try
            {
                viewModel = new StaffCourseAllocationViewModel();
                ViewBag.Session = viewModel.SessionSelectList;
                ViewBag.Semester = new SelectList(new List<Semester>(), ID, NAME);
                ViewBag.ProgrammeType = viewModel.ProgrammeTypeSelectList;
                ViewBag.Level = viewModel.LevelSelectList;
            }
            catch (Exception ex)
            {
                SetMessage("Error Occured" + ex.Message, Message.Category.Error);
            }

            return View(viewModel);
        }
        [HttpPost]
        public ActionResult AllocatedCourses(StaffCourseAllocationViewModel viewModel)
        {
            try
            {
                if (viewModel != null)
                {
                    CourseAllocationLogic courseAllocationLogic = new CourseAllocationLogic();
                    viewModel.CourseAllocationList = courseAllocationLogic.GetModelsBy(p => p.Level_Id == viewModel.CourseAllocation.Level.Id &&
                                                                                            p.Programme_Type_Id == viewModel.CourseAllocation.ProgrammeType.Id &&
                                                                                            p.Semester_Id == viewModel.CourseAllocation.Semester.Id &&
                                                                                            p.Session_Id == viewModel.CourseAllocation.Session.Id
                                                                                        );
                }

                KeepDropDownState(viewModel);
            }
            catch (Exception ex)
            {
                SetMessage("Error: " + ex.Message, Message.Category.Error);
            }

            return View(viewModel);
        }
       
        public ActionResult AllocateCourse()
        {
            try
            {
                viewModel = new StaffCourseAllocationViewModel();
                ViewBag.Session = viewModel.SessionSelectList;
                ViewBag.Semester = new SelectList(new List<Semester>(), ID, NAME);
                ViewBag.ProgrammeType = viewModel.ProgrammeTypeSelectList;
                ViewBag.User = viewModel.StaffSelectList;
                ViewBag.Level = viewModel.LevelSelectList;
                ViewBag.Department = new SelectList(new List<Department>(), ID, NAME);
                ViewBag.Course = new SelectList(new List<Course>(), ID, "CodeName");
            }
            catch (Exception ex)
            {
                SetMessage("Error: " + ex.Message, Message.Category.Error);
            }
            return View();
        }
        [HttpPost]
        public ActionResult AllocateCourse(StaffCourseAllocationViewModel viewModel)
        {
            try
            {
                if (viewModel.CourseAllocation != null)
                {
                    CourseAllocationLogic courseAllocationLogic = new CourseAllocationLogic();
                    List<CourseAllocation> courseAllocationList = courseAllocationLogic.GetModelsBy(p => p.Level_Id == viewModel.CourseAllocation.Level.Id &&
                                                                                                        p.Programme_Type_Id == viewModel.CourseAllocation.ProgrammeType.Id &&
                                                                                                        p.Semester_Id == viewModel.CourseAllocation.Semester.Id &&
                                                                                                        p.Session_Id == viewModel.CourseAllocation.Session.Id &&
                                                                                                        p.Course_Id == viewModel.CourseAllocation.Course.Id &&
                                                                                                        p.Department_Id == viewModel.CourseAllocation.Department.Id &&
                                                                                                        p.User_Id == viewModel.CourseAllocation.User.Id
                                                                                                        );
                    if (courseAllocationList.Count == 0)
                    {
                        courseAllocationLogic.Create(viewModel.CourseAllocation);
                        SetMessage("Course Allocated", Message.Category.Information);
                        return RedirectToAction("AllocateCourse");
                    }
                    else
                    {
                        SetMessage("Another Staff has already been assigned to this Course", Message.Category.Error);
                        KeepAllDropDownState(viewModel);
                        return View();
                    }
                }
            }
            catch (Exception ex)
            {
                SetMessage("Error: " + ex.Message, Message.Category.Error);
            }
            return View();
        }
        public ActionResult StaffReportSheet()
        {
            try
            {
                viewModel = new StaffCourseAllocationViewModel();
                ViewBag.Session = viewModel.SessionSelectList;
                ViewBag.Semester = new SelectList(new List<Semester>(), ID, NAME);
                ViewBag.Level = viewModel.LevelSelectList;
                
            }
            catch (Exception ex)
            {       
                SetMessage("Error! " + ex.Message, Message.Category.Error);
            }
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult StaffReportSheet(StaffCourseAllocationViewModel viewModel)
        {
            try
            {
                if (viewModel != null)
                {
                    CourseAllocationLogic courseAllocationLogic = new CourseAllocationLogic();
                    UserLogic userLogic = new UserLogic();
                    Model.Model.User user = userLogic.GetModelBy(u => u.User_Name == User.Identity.Name);
                    if (user.Role.Id == 2)
                    {
                        viewModel.CourseAllocationList = courseAllocationLogic.GetModelsBy(p => p.Level_Id == viewModel.Level.Id && p.Semester_Id == viewModel.Semester.Id && p.Session_Id == viewModel.Session.Id ); 
                 
                    }
                    else
                    {
                        viewModel.CourseAllocationList = courseAllocationLogic.GetModelsBy(p => p.Level_Id == viewModel.Level.Id && p.Semester_Id == viewModel.Semester.Id && p.Session_Id == viewModel.Session.Id && p.USER.User_Name == User.Identity.Name);
                    } 
                }
                if (viewModel.CourseAllocationList.Count == 0)
                {
                   SetMessage("No Course To Display For User", Message.Category.Error); 
                }                                    

                KeepDropDownState(viewModel);
            }
            catch (Exception ex)
            {
                SetMessage("Error! " + ex.Message, Message.Category.Error);
            }
            
            return View(viewModel);
        }
        public ActionResult StaffDownloadReportSheet(int Session_Id, int Semester_Id, int Programme_Id, int Department_Id, int Level_Id, int Course_Id)
        {
            try
            { 
                return RedirectToAction("ResultSheet", new { area = "admin", controller = "Report", levelId = Level_Id, semesterId = Semester_Id, progId = Programme_Id, deptId = Department_Id, sessionId = Session_Id, courseId = Course_Id });

            }
            catch (Exception)
            {  
                throw;
            }

        }
        public JsonResult GetDepartments(string id)
        {
            try
            {
                if (string.IsNullOrEmpty(id))
                {
                    return null;
                }
                ProgrammeTypeLogic programmeTypeLogic = new ProgrammeTypeLogic();
                ProgrammeType programmeType = new ProgrammeType() { Id = Convert.ToInt32(id) };
                PROGRAMME_TYPE entityProgrammeType = programmeTypeLogic.GetEntityBy(pt => pt.ProgrammeTypeId == programmeType.Id);
                DepartmentLogic departmentLogic = new DepartmentLogic();
                List<DEPARTMENT> departments = departmentLogic.GetBy(entityProgrammeType);

                return Json(new SelectList(departments, "DepartmentId", NAME), JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public JsonResult GetSemester(string id)
        {
            try
            {
                if (string.IsNullOrEmpty(id))
                {
                    return null;
                }

                Session session = new Session() { Id = Convert.ToInt32(id) };
                List<SessionSemester> sessionSemesterList = new List<SessionSemester>();
                SessionSemesterLogic sessionSemesterLogic = new SessionSemesterLogic();

Abundance_Rm/Areas/Admin/Views/StaffCourseAllocation/AttendanceReport.cshtml
@{
    ViewBag.Title = "Attendance Sheet";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


    <script src="~/Scripts/jquery-1.10.2.min.js"></script>

    <script src="~/Scripts/responsive-tabs.js"></script>

    <script type="text/javascript">
               function resizeIframe(obj) {
            obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
        }
    </script>

<div style="color:black">
    <h3>
        Attendance Sheet
    </h3>
</div>

<div class="alert alert-dismissible alert-success">
    <p>
        <b>Attendance Sheet </b>
    </p>
</div>

<iframe src="@Url.Content("~/Reports/Presenter/Result/AttendanceReport.aspx?sessionId=" + (string)ViewBag.SessionId + "&semesterId=" + (string)ViewBag.SemesterId + "&levelId=" + (string)ViewBag.LevelId + "&courseId=" + ViewBag.CourseId + "&programmeId=" + (string)ViewBag.ProgrammeId + "&departmentId=" + (string)ViewBag.DepartmentId)" style="width:100%; " frameborder="0" scrolling="no" id="iframe" onload='javascript:resizeIframe(this);'></iframe>


<br />

Abundance_Rm/Areas/Admin/Views/StaffCourseAllocation/DownloadAttendanceSheet.cshtml
@model Abundance_Nk.Web.Areas.Admin.ViewModels.StaffCourseAllocationViewModel
@{
    ViewBag.Title = "DownloadAttendanceSheet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (TempData["Message"] != null)
{
    @Html.Partial("_Message", (Abundance_Nk.Model.Model.Message)TempData["Message"])
}

<script src="~/Scripts/jquery-1.11.1.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {

        function populateCourses() {
            $("#Course").empty();
            var values = new Array();
            //vals = [$("#Department").val(), $("#Level").val(), $("#Semester").val()];
            values[0] = $("#Department").val();
            values[1] = $("#Level").val();
            values[2] = $("#Semester").val();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetCourses", "StaffCourseAllocation")', // Calling json method
                traditional: true,
                data: {ids :values},
                    // Get Selected Country ID.
                    success: function (courses) {

                        $.each(courses, function (i, course) {
                            $("#Course").append('<option value="' + course.Value + '">' +
                                 course.Text + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Failed to retrieve courses.' + ex);
                    }
                });

        }
        //Programme Drop down Selected-change event
        $("#Programme").change(function () {
            if ($("#Department").val() > 0 && $("#Level").val() > 0 && $("#Semester").val() > 0) {
                populateCourses();
            }
            $("#Department").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetDepartments", "StaffCourseAllocation")', // Calling json method
                dataType: 'json',
                data: { id: $("#Programme").val() },
                // Get Selected Country ID.
                success: function (departments) {
                    $("#Department").append('<option value="' + 0 + '">' +
                            '-- Select Department --' + '</option>');
                    $.each(departments, function (i, department) {
                        $("#Department").append('<option value="' + department.Value + '">' +
                             department.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve departments.' + ex);
                }
            });
            return false;
        })
        //Session Drop down Selected change event
        $("#Session").change(function () {
            if ($("#Department").val() > 0 && $("#Level").val() > 0 && $("#Semester").val() > 0)
            {
                populateCourses();
            }

            $("#Semester").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetSemester", "StaffCourseAllocation")', // Calling json method
                dataType: 'json',
                data: { id: $("#Session").val() },
                // Get Selected Country ID.
                success: function (semesters) {
                    $("#Semester").append('<option value="' + 0 + '">' +
                           '-- Select Semester --' + '</option>');
                    $.each(semesters, function (i, semester) {
                        $("#Semester").append('<option value="' + semester.Value + '">' +
                             semester.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve semesters.' + ex);
                }
            });
            return false;
        })
        $("#Department").change(function () {
            if ($("#Department").val() > 0 && $("#Level").val() > 0 && $("#Semester").val() > 0) {
                populateCourses();
            }
        });
        $("#Session").change(function () {
            if ($("#Department").val() > 0 && $("#Level").val() > 0 && $("#Semester").val() > 0) {
                populateCourses();
            }
        });
        $("#Level").change(function () {
            if ($("#Department").val() > 0 && $("#Level").val() > 0 && $("#Semester").val() > 0) {
                populateCourses();
            }

        });




    });
</script>

@using (Html.BeginForm("AttendanceReport", "StaffCourseAllocation", new { area = "Admin" }, FormMethod.Post))
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-fw fa-download"></i>Download Result Sheet</h3>
        </div>
        <div class="panel-body">

            <div class="form-group">
                @Html.LabelFor(model => model.Session.Name, "Session", new { @class = "col-sm-2 control-label " })
                <div class="col-sm-10">
                    @Html.DropDownListFor(model => model.Session.Id, (IEnumerable<SelectListItem>)ViewBag.Session, new { @class = "form-control", @id = "Session" })
                    @Html.ValidationMessageFor(model => model.Session.Id, null, new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Semester.Name, "Semester", new { @class = "col-sm-2 control-label " })
                <div class="col-sm-10">
                    @Html.DropDownListFor(model => model.Semester.Id, (IEnumerable<SelectListItem>)ViewBag.Semester, new { @class = "form-control", @id = "Semester" })
                    @Html.ValidationMessageFor(model => model.Semester.Id, null, new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Programme.Name, "Programme", new { @class = "col-sm-2 control-label " })
                <div class="col-sm-10">
                    @Html.DropDownListFor(model => model.Programme.Id, (IEnumerable<SelectListItem>)ViewBag.Programme, new { @class = "form-control", @id = "Programme" })
                    @Html.ValidationMessageFor(model => model.Programme.Id, null, new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Department.Name, "Department", new { @class = "col-sm-2 control-label " })
                <div class="col-sm-10">
                    @Html.DropDownListFor(model => model.Department.Id, (IEnumerable<SelectListItem>)ViewBag.Department, new { @class = "form-control", @id = "Department" })
                    @Html.ValidationMessageFor(model => model.Department.Id, null, new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Level.Name, "Level", new { @class = "col-sm-2 control-label " })
                <div class="col-sm-10">
                    @Html.DropDownListFor(model => model.Level.Id, (IEnumerable<SelectListItem>)ViewBag.Level, new { @class = "form-control", @id = "Level" })
                    @Html.ValidationMessageFor(model => model.Level.Id, null, new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Course.Name, "Course", new { @class = "col-sm-2 control-label " })
                <div class="col-sm-10">
                    @Html.DropDownListFor(model => model.Course.Id, (IEnumerable<SelectListItem>)ViewBag.Course, new { @class = "form-control", @id = "Course" })
                    @Html.ValidationMessageFor(model => model.Course.Id, null, new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                    <input class="btn btn-success mr5 " type="submit" name="submit" id="submit" value="Download Here" />

                </div>
            </div>

        </div>
    </div>

}

Abundance_Rm/Areas/Admin/Views/StaffCourseAllocation/DownloadResultSheet.cshtml
@model Abundance_Nk.Web.Areas.Admin.ViewModels.StaffCourseAllocationViewModel
@{
    ViewBag.Title = "DownloadResultSheet";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@if (TempData["Message"] != null)
{
    @Html.Partial("_Message", (Abundance_Nk.Model.Model.Message)TempData["Message"])
}

<script src="~/Scripts/jquery-1.11.1.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {

        function populateCourses() {
            $("#Course").empty();
            var values = new Array();
            //vals = [$("#Department").val(), $("#Level").val(), $("#Semester").val()];
            values[0] = $("#Department").val();
            values[1] = $("#Level").val();
            values[2] = $("#Semester").val();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetCourses", "StaffCourseAllocation")', // Calling json method
                traditional: true,
                data: {ids :values},
                    // Get Selected Country ID.
                    success: function (courses) {

                        $.each(courses, function (i, course) {
                            $("#Course").append('<option value="' + course.Value + '">' +
                                 course.Text + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Failed to retrieve courses.' + ex);
                    }
                });

        }
        //Programme Drop down Selected-change event
        $("#Programme").change(function () {
            if ($("#Department").val() > 0 && $("#Level").val() > 0 && $("#Semester").val() > 0) {
                populateCourses();
            }
            $("#Department").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetDepartments", "StaffCourseAllocation")', // Calling json method
                dataType: 'json',
                data: { id: $("#Programme").val() },
                // Get Selected Country ID.
                success: function (departments) {
                    $("#Department").append('<option value="' + 0 + '">' +
                            '-- Select Department --' + '</option>');
                    $.each(departments, function (i, department) {
                        $("#Department").append('<option value="' + department.Value + '">' +
                             department.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve departments.' + ex);
                }
            });
            return false;
        })
        //Session Drop down Selected change event
        $("#Session").change(function () {
            if ($("#Department").val() > 0 && $("#Level").val() > 0 && $("#Semester").val() > 0)
            {
                populateCourses();
            }

            $("#Semester").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetSemester", "StaffCourseAllocation")', // Calling json method
                dataType: 'json',
                data: { id: $("#Session").val() },
                // Get Selected Country ID.
                success: function (semesters) {
                    $("#Semester").append('<option value="' + 0 + '">' +
                           '-- Select Semester --' + '</option>');
                    $.each(semesters, function (i, semester) {
                        $("#Semester").append('<option value="' + semester.Value + '">' +
                             semester.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve semesters.' + ex);
                }
            });
            return false;
        })
        $("#Department").change(function () {
            if ($("#Department").val() > 0 && $("#Level").val() > 0 && $("#Semester").val() > 0) {
                populateCourses();
            }
        });
        $("#Session").change(function () {
            if ($("#Department").val() > 0 && $("#Level").val() > 0 && $("#Semester").val() > 0) {
                populateCourses();
            }
        });
        $("#Level").change(function () {
            if ($("#Department").val() > 0 && $("#Level").val() > 0 && $("#Semester").val() > 0) {
                populateCourses();
            }

        });




    });
</script>

@using (Html.BeginForm("DownloadResultSheet", "StaffCourseAllocation", new { area = "Admin" }, FormMethod.Post))
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-fw fa-download"></i>Download Result Sheet</h3>
        </div>
        <div class="panel-body">

            <div class="form-group">
                @Html.LabelFor(model => model.Session.Name, "Session", new { @class = "col-sm-2 control-label " })
                <div class="col-sm-10">
                    @Html.DropDownListFor(model => model.Session.Id, (IEnumerable<SelectListItem>)ViewBag.Session, new { @class = "form-control", @id = "Session" })
                    @Html.ValidationMessageFor(model => model.Session.Id, null, new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Semester.Name, "Semester", new { @class = "col-sm-2 control-label " })
                <div class="col-sm-10">
                    @Html.DropDownListFor(model => model.Semester.Id, (IEnumerable<SelectListItem>)ViewBag.Semester, new { @class = "form-control", @id = "Semester" })
                    @Html.ValidationMessageFor(model => model.Semester.Id, null, new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Programme.Name, "Programme", new { @class = "col-sm-2 control-label " })
                <div class="col-sm-10">
                    @Html.DropDownListFor(model => model.Programme.Id, (IEnumerable<SelectListItem>)ViewBag.Programme, new { @class = "form-control", @id = "Programme" })
                    @Html.ValidationMessageFor(model => model.Programme.Id, null, new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Department.Name, "Department", new { @class = "col-sm-2 control-label " })
                <div class="col-sm-10">
                    @Html.DropDownListFor(model => model.Department.Id, (IEnumerable<SelectListItem>)ViewBag.Department, new { @class = "form-control", @id = "Department" })
                    @Html.ValidationMessageFor(model => model.Department.Id, null, new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Level.Name, "Level", new { @class = "col-sm-2 control-label " })
                <div class="col-sm-10">
                    @Html.DropDownListFor(model => model.Level.Id, (IEnumerable<SelectListItem>)ViewBag.Level, new { @class = "form-control", @id = "Level" })
                    @Html.ValidationMessageFor(model => model.Level.Id, null, new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Course.Name, "Course", new { @class = "col-sm-2 control-label " })
                <div class="col-sm-10">
                    @Html.DropDownListFor(model => model.Course.Id, (IEnumerable<SelectListItem>)ViewBag.Course, new { @class = "form-control", @id = "Course" })
                    @Html.ValidationMessageFor(model => model.Course.Id, null, new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                    <input class="btn btn-success mr5 " type="submit" name="submit" id="submit" value="Download Here" />

                </div>
            </div>

        </div>
    </div>

}

Abundance_Rm/Areas/Admin/Views/StaffCourseAllocation/ResultUploadSheet.cshtml
@model Abundance_Nk.Web.Areas.Admin.ViewModels.StaffCourseAllocationViewModel
@{
    ViewBag.Title = "UploadResultSheet";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@if (TempData["Message"] != null)
{
    @Html.Partial("_Message", (Abundance_Nk.Model.Model.Message)TempData["Message"])
}




@using (Html.BeginForm("UploadResultSheet", "StaffCourseAllocation", new { area = "Admin" }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-fw fa-upload"></i>Upload Result Sheet</h3>
        </div>
        <div class="panel-body">
            <div class="alert alert-warning alert-dismissable"><h4>Endeavour to Cross Check Fields and Verify Excel Data</h4></div>
            <br />
            @if (Model == null || Model.resultFormatList == null)
            {
                return;
            }
            @if (Model != null && Model.resultFormatList.Count > 0)
            {
                <table class="table table-responsive table-striped">
                    <tr>
                        <th>S/N</th>
                        <th>FULLNAME</th>
                        <th>MATRIC NUMBER</th>
                        <th>GRADE</th>
                    
                    </tr>
                    @for (int i = 0; i < Model.resultFormatList.Count; i++)
                    {
                        <tr>
                            <td>
                                @Model.resultFormatList[i].SN
                            </td>
                            <td>
                                @Model.resultFormatList[i].Fullname
                            </td>
                            <td>
                                @Model.resultFormatList[i].MatricNo
                            </td>
                            <td>@Model.resultFormatList[i].GRADE</td>
                           
                        </tr>
                    }
                </table>
                <br />
                <div class="form-group" style="text-align:center">

                    <div class="col-sm-10 pull-left">
                        @*<input class="btn btn-success mr5 " type="submit" name="submit" id="submit" value="Save Upload" />*@
                        @Html.ActionLink("Save Upload", "SaveUploadedResultSheet", new { controller = "StaffCourseAllocation", area = "Admin" }, new { @class = "btn btn-success mr5" })
                    </div>
                </div>
            }
        </div>

    </div>

}