Abundance_Rm/Areas/Admin/Controllers/TranscriptController.cs
using Abundance_Rm.Areas.Admin.ViewModel;
using Abundance_Rm.Business;
using Abundance_Rm.Model.Entity;
using Abundance_Rm.Model.Model;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity.Validation;
using System.Data.SqlClient;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Transactions;
using System.Web.Mvc;
using Abundance_Rm.Controllers;
using Abundance_Rm.Models;
using Newtonsoft.Json;


namespace Abundance_Rm.Areas.Admin.Controllers
{

    [Authorize(Roles = "Admin,Records")]
    public class TranscriptController : BaseController
    {
        public const string ID = "Id";
        public const string NAME = "Name";
        //SqlConnection conn = new SqlConnection("data source=.;initial catalog=VS_ABSU;integrated security=True;");
        SqlConnection conn = new SqlConnection("data source=97.74.6.243;initial catalog=VS_ABSU;User ID=support;Password=8n4H!Lo65");



        // GET: Admin/Transcript
        public ActionResult StudentDisplay()
        {
            try
            {
                TranscriptViewModel tanscriptViewModel = new TranscriptViewModel();
                ViewBag.ProgrammeTypeId = tanscriptViewModel.ProgrammeTypeSelectListItem;
                ViewBag.DepartmentId = new SelectList(new List<Department>(), ID, NAME);
                ViewBag.SessionId = tanscriptViewModel.YearOfEntrySelectListItem;
                return View();
            }
            catch (Exception)
            {

                throw;
            }
        }
        [HttpPost]
        public ActionResult StudentDisplay(TranscriptViewModel viewModel)
        {
            try
            {
                SessionLogic sessionLogic = new SessionLogic();
                SESSION session = new SESSION();
                StudentLogic studentLogic = new StudentLogic();
                ProgrammeTypeLogic programmeTypeLogic = new ProgrammeTypeLogic();
                DepartmentLogic departmentLogic = new DepartmentLogic();
                List<DEPARTMENT> departments = departmentLogic.GetBy(viewModel.ProgrammeType);
                session = sessionLogic.GetEntityBy(p => p.SessionId == viewModel.Session.SessionId);
                string yearOfGraduation = session.Name.Trim();
                List<STUDENT> studentList = studentLogic.GetBy(yearOfGraduation, viewModel.Department, viewModel.ProgrammeType);
                viewModel.StudentList = studentList;
                viewModel.YearOfEntry = yearOfGraduation;
                ViewBag.ProgrammeTypeId = new SelectList(programmeTypeLogic.GetAll(), ID, NAME, viewModel.ProgrammeType.ProgrammeTypeId);
                ViewBag.DepartmentId = new SelectList(departments, "DepartmentId", NAME, viewModel.Department.DepartmentId);
                ViewBag.SessionId = new SelectList(sessionLogic.GetAll(), ID, NAME, viewModel.Session.SessionId);
                return View(viewModel);
            }
            catch (Exception)
            {

                throw;
            }

        }
        public ActionResult StudentClassList()
        {
            try
            {
                TranscriptViewModel tanscriptViewModel = new TranscriptViewModel();
                ViewBag.ProgrammeTypeId = tanscriptViewModel.ProgrammeTypeSelectListItem;
                ViewBag.DepartmentId = new SelectList(new List<DEPARTMENT>(), ID, NAME);
                ViewBag.SessionId = tanscriptViewModel.YearOfEntrySelectListItem;
                return View();
            }
            catch (Exception)
            {

                throw;
            }

        }
        [HttpPost]
        public ActionResult StudentClassList(TranscriptViewModel viewModel)
        {
            try
            {
                SessionLogic sessionLogic = new SessionLogic();
                SESSION session = new SESSION();
                long deptId = viewModel.Department.DepartmentId;
                long progId = viewModel.ProgrammeType.ProgrammeTypeId;
                session = sessionLogic.GetEntityBy(p => p.SessionId == viewModel.Session.SessionId);
                string yearOfGraduation = session.Name.Trim();
                return RedirectToAction("ClassListReport", new { area = "admin", controller = "Report", deptId = deptId, progId = progId, yearOfGraduation = yearOfGraduation });
                // Response.Redirect(@"~/Report/Presenter/StudentClassList.aspx?deptId=" + deptId + "&progId=" + progId + "&yearOfEntry=" + yearOfEntry);
                // return new EmptyResult();
            }
            catch (Exception)
            {

                throw;
            }

        }
        public ActionResult TranscriptReport(string Id)
        {
            return RedirectToAction("TranscriptReport", new { area = "admin", controller = "Report", id = Id });
            // Response.Redirect(@"~/Report/Presenter/ResultTranscript.aspx?id=" + Id);
            //return new EmptyResult();

        }
        public JsonResult GetDepartments(string id)
        {
            try
            {
                if (string.IsNullOrEmpty(id))
                {
                    return null;
                }

                PROGRAMME_TYPE programmeType = new PROGRAMME_TYPE() { ProgrammeTypeId = Convert.ToInt32(id) };
                DepartmentLogic departmentLogic = new DepartmentLogic();
                List<DEPARTMENT> departments = departmentLogic.GetBy(programmeType);

                return Json(new SelectList(departments, "DepartmentId", NAME), JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult CreateSession()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateSession(Session model)
        {
            try
            {
                if (model != null && model.Name.Contains('/'))
                {

                    SessionLogic sessionLogic = new SessionLogic();

                    model.Description = model.Name + " " + "SESSION";
                    var duplicateSession = sessionLogic.GetModelBy(s => s.Name.Contains(model.Name));
                    if (duplicateSession == null)
                    {
                        Session createdSession = sessionLogic.Create(model);
                        if (createdSession != null)
                        {
                            SessionSemesterLogic sessionSemesterLogic = new SessionSemesterLogic();
                            var lastSessionSemester = sessionSemesterLogic.GetAll().LastOrDefault();

                            if (lastSessionSemester != null)
                            {
                                for (int i = 1; i < 3; i++)
                                {

                                    SessionSemester sessionSemester = new SessionSemester();
                                    sessionSemester.SequenceNumber = lastSessionSemester.SequenceNumber + i;
                                    sessionSemester.Session = createdSession;
                                    sessionSemester.Semester = new Semester()
                                    {
                                        Id = i
                                    };
                                    sessionSemester.StartDate = DateTime.Now;
                                    sessionSemester.EndDate = DateTime.Now;
                                    var createdSessionSemester = sessionSemesterLogic.Create(sessionSemester);
                                }
                                SetMessage("Operation Succesful", Message.Category.Information);
                            }
                            else
                            {
                                SetMessage("Input String was not in the correct Format", Message.Category.Error);
                            }

                        }
                    }
                    else
                    {
                        SetMessage("Error Occured! Session Already Exist", Message.Category.Error);
                    }

                }
            }
            catch (Exception ex)
            {

                throw;
            }
            ModelState.Clear();
            return View();
        }
        public ActionResult EditSession(int? editId)
        {
            Session session = new Session();
            try
            {
                if (editId > 0)
                {
                    SessionLogic courseLogic = new SessionLogic();
                    session = courseLogic.GetModelBy(s => s.SessionId == editId);
                }
            }
            catch (Exception ex)
            {

                throw;
            }
            return View(session);
        }
        public ActionResult SaveSession(Session session)
        {
            try
            {

                if (session != null)
                {


                    SessionLogic sessionLogic = new SessionLogic();

                    var checkduplicate = sessionLogic.GetModelBy(da => da.Name == session.Name);
                    if (checkduplicate == null)
                    {
                        bool modifiedSession = sessionLogic.Modify(session);
                        if (modifiedSession)
                        {
                            SetMessage("Operation Successful", Message.Category.Information);

                        }
                        else
                        {
                            SetMessage("Error Occured Session Could not be Modified", Message.Category.Error);
                        }
                    }
                    else

Abundance_Rm/Areas/Admin/Views/Transcript/AddExtraCourse.cshtml
@model Abundance_Rm.Areas.Admin.ViewModel.TranscriptViewModel
@{
    ViewBag.Title = "AddExtraCourse";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/jquery-1.11.1.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {

        //Programme Drop down Selected-change event
        $("#Programme").change(function () {

            $("#Department").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetDepartments", "Transcript")', // Calling json method
                dataType: 'json',
                data: { id: $("#Programme").val() },
                // Get Selected Country ID.
                success: function (departments) {
                    $("#Department").append('<option value="' + 0 + '">' +
                        '-- Select Department --' + '</option>');
                    $.each(departments, function (i, department) {
                        $("#Department").append('<option value="' + department.Value + '">' +
                            department.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve departments.' + ex);
                }
            });
            return false;
        });
        //Session Drop down Selected change event
        $("#Session").change(function () {

            $("#Semester").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetSemester", "Transcript")', // Calling json method
                dataType: 'json',
                data: { id: $("#Session").val() },
                // Get Selected Country ID.
                success: function (semesters) {
                    $("#Semester").append('<option value="' + 0 + '">' +
                        '-- Select Semester --' + '</option>');
                    $.each(semesters, function (i, semester) {
                        $("#Semester").append('<option value="' + semester.Value + '">' +
                            semester.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve semesters.' + ex);
                }
            });
            return false;
        });

    });

    function CheckAll() {
        if ($('#CourseId').is(':checked')) {
            $('.checkAll').prop('checked', true);
        }
        else {
            $('.checkAll').prop('checked', false);
        }
    }

    function CheckAllCarryOver() {
        if ($('#CarryOverId').is(':checked')) {
            $('.checkAllCarryOver').prop('checked', true);
        }
        else {
            $('.checkAllCarryOver').prop('checked', false);
        }
    }

</script>
@using (Html.BeginForm("SaveAddedCourse", "Transcript", new { area = "Admin" }, FormMethod.Post))
{
    <div class="col-md-12">

        <div>
            @if (TempData["Message"] != null)
            {
                @Html.Partial("_Message", (Abundance_Rm.Model.Model.Message) TempData["Message"])
            }
        </div>

        <div class="panel panel-default">
            <div class="panel-heading panel-dark-head">
                <h4>Register Course</h4>
            </div>
            <div class="panel-body">
                <div class="col-md-12">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Student.Person.FullName, new {@class = "col-sm-2 control-label "})
                            <div class="col-sm-10">
                                @Html.TextBoxFor(model => model.Student.Person.FullName, new {@class = "form-control", @disabled = "disabled"})
                            </div>
                        </div>
                    </div>
                    <div class=" col-lg-12 col-md-12 col-sm-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Student.EntryRegNo, "Matric Number", new {@class = "col-sm-2 control-label "})
                            <div class="col-sm-10">
                                @Html.TextBoxFor(model => model.Student.EntryRegNo, new {@class = "form-control", @disabled = "disabled"})
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.StudentLevel.ProgrammeType.Name, "Programme", new {@class = "col-sm-2 control-label "})
                            <div class="col-sm-10">
                                @Html.TextBoxFor(model => model.StudentLevel.ProgrammeType.Name, new {@class = "form-control", @disabled = "disabled"})
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.StudentLevel.Department.Name, "Department", new {@class = "col-sm-2 control-label "})
                            <div class="col-sm-10">
                                @Html.TextBoxFor(model => model.StudentLevel.Department.Name, new {@class = "form-control", @disabled = "disabled"})
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Semester.Name, "Semester", new {@class = "col-sm-2 control-label "})
                            <div class="col-sm-10">
                                @Html.TextBoxFor(model => model.Semester.Name, new {@class = "form-control", @disabled = "disabled"})
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Session.Name, "Session", new {@class = "col-sm-2 control-label "})
                            <div class="col-sm-10">
                                @Html.DropDownListFor(model => model.Session.SessionId, (IEnumerable<SelectListItem>) ViewBag.Session, new {@class = "form-control", required = true})
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.StudentLevel.Level.Name, "Level", new {@class = "col-sm-2 control-label "})
                            <div class="col-sm-10">
                                @Html.DropDownListFor(model => model.StudentLevel.Level.Id, (IEnumerable<SelectListItem>) ViewBag.Level, new {@class = "form-control", required = true})
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        @if (Model.ProgrammeCoures == null)
        {
            return;
        }
        @if (Model.ProgrammeCoures.Count > 0)
        {
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-12">

                        @Html.HiddenFor(model => model.Student.EntryRegNo) 
                        @Html.HiddenFor(model => model.Student.Id)
                            @Html.HiddenFor(model => model.Semester.Id)
                            @Html.HiddenFor(model => model.StudentLevel.ProgrammeType.Id)
                            @Html.HiddenFor(model => model.StudentLevel.Department.Id)
                            @Html.HiddenFor(model => model.StudentLevel.Department.Name)
                            @Html.HiddenFor(model => model.StudentLevel.Level.Id)
                            @Html.HiddenFor(model => model.StudentLevel.Level.Name)

                            <table class="table table-bordered table-hover table-striped table-responsive">
                                <tr>
                                    <th>Level</th>
                                    <th>Course Code</th>
                                    <th>Course Name</th>
                                    <th>Course Unit</th>
                                    <th>Course Semester</th>
                                    <th>Grade</th>
                                    <th>@*<input type="checkbox" id="CourseId" onclick="CheckAll()" />*@ Select Course</th>
                                    <th>@*<input type="checkbox" id="CarryOverId" onclick="CheckAllCarryOver()" />*@ Carry Over</th>
                                </tr>
                                @for (int i = 0; i < Model.ProgrammeCoures.Count; i++)
                                {
                                    <tr>
                                        @Html.HiddenFor(model => model.ProgrammeCoures[i].Id)
                                        @Html.HiddenFor(model => model.ProgrammeCoures[i].Unit)
                                        @Html.HiddenFor(model => model.ProgrammeCoures[i].Course.Course_Code)
                                        @Html.HiddenFor(model => model.ProgrammeCoures[i].Course.Name)
                                        @Html.HiddenFor(model => model.ProgrammeCoures[i].Programme.department.Name)
                                        @Html.HiddenFor(model => model.ProgrammeCoures[i].Level.Name)
                                        @Html.HiddenFor(model => model.ProgrammeCoures[i].Semester.Id)
                                        @Html.HiddenFor(model => model.ProgrammeCoures[i].Semester.Name)
                                        @Html.HiddenFor(model => model.Session.SessionId)

                                        <td>@Model.ProgrammeCoures[i].Level.Name</td>
                                        <td>@Model.ProgrammeCoures[i].Course.Course_Code</td>
                                        <td>@Model.ProgrammeCoures[i].Course.Name</td>
                                        <td>@Model.ProgrammeCoures[i].CourseUnit</td>
                                        <td>@Model.ProgrammeCoures[i].Semester.Name</td>

                                        <td>@Html.DropDownListFor(m => m.ProgrammeCoures[i].Grade, (IEnumerable<SelectListItem>) ViewData["fCourse" + i], new {@class = "form-control"})</td>
                                        <td>@Html.CheckBoxFor(model => model.ProgrammeCoures[i].IsRegistered, new {@type = "checkbox", @class = "checkAll"})</td>
                                        <td>@Html.CheckBoxFor(model => model.ProgrammeCoures[i].IsCarryOverCourse, new {@type = "checkbox", @class = "checkAllCarryOver"})</td>
                                    </tr>
                                }
                            </table>
                            <br/>
                            <div class="row">
                                <div class="form-group">
                                    <div class="col-sm-12">
                                        <input class="btn btn-success mr5" type="submit" name="submit" id="submit" value="Save"/>
                                    </div>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        }

    </div>
}




Abundance_Rm/Areas/Admin/Views/Transcript/CreateDepartment.cshtml
@model Abundance_Rm.Areas.Admin.ViewModel.UploadResultViewModel
@{
    ViewBag.Title = "CreateDepartment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/dataTables.css" rel="stylesheet" />


<script src="~/Scripts/jquery-1.11.1.min.js"></script>
<script src="~/Scripts/jquery-2.1.3.js"></script>
<link href="~/Content/bootstrap.css" rel="stylesheet" />

<script src="~/Scripts/jquery-1.11.1.min.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/dataTables.js"></script>



<script type="text/javascript">
    $(function() {


        $("#ProgrammetypeId").change(function() {
            $("#DeparmentId").empty();

            var progId = $("#ProgrammetypeId").val();

            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetDepartments", "UploadResult")', // Calling json method
                dataType: 'json',
                data: { id: progId },
                // Get Selected Country ID.
                success: function(departments) {
                    $("#DeparmentId").append('<option value="' + 0 + '">--Select--</option>');
                    $.each(departments, function(i, department) {
                        $("#DeparmentId").append('<option value="' + department.Value + '">' +
                            department.Text + '</option>');
                    });
                },
                error: function(ex) {
                    alert('Failed to retrieve departments.' + ex);
                }
            });
            return false;
        });


    });

</script>

<br />

@if (TempData["Message"] != null)
{
    @Html.Partial("_Message", (Abundance_Rm.Model.Model.Message)TempData["Message"])
}


@using (Html.BeginForm("CreateDepartment", "Transcript", new { area = "admin" }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="panel panel-default">
        <div class="panel-heading"><h4>Create</h4></div>
        <div class="panel-body">

            <div class="row">

                <hr style="margin-top: 0" />
                <div class="col-md-12">

                    <div class="row">

                        <div class="col-md-6">
                            <div class="form-group">

                                @Html.LabelFor(model => model.DepartmentModel.Name, "Department Name", new {@class = "control-label "})
                                @Html.TextBoxFor(model => model.DepartmentModel.Name, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.DepartmentModel.Name, null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">

                                @Html.LabelFor(model => model.DepartmentModel.Department_Code, "Department Code", new { @class = "control-label " })
                                @Html.TextBoxFor(model => model.DepartmentModel.Department_Code, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.DepartmentModel.Department_Code, null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">

                                @Html.LabelFor(model => model.DepartmentModel.faculty.Id, "Faculty", new { @class = "control-label " })
                                @Html.DropDownListFor(model => model.DepartmentModel.faculty.Id, (IEnumerable<SelectListItem>)ViewBag.FacultyId, new { @class = "form-control", @placeholder = "Enter Department Code e.g GSS 102,GSS 104" })
                                @Html.ValidationMessageFor(model => model.DepartmentModel.faculty.Id, null, new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>

                    <div class="row">
                        <div class="form-group">
                            <div class="col--2"></div>
                            <div class="col-sm-10">
                                <input class="btn btn-success mr5" type="submit" name="submit" value="Create" />

                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
}

Abundance_Rm/Areas/Admin/Views/Transcript/CreateFaculty.cshtml
@model Abundance_Rm.Model.Model.Faculty
@{
    ViewBag.Title = "CreateDegreeAward";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/dataTables.css" rel="stylesheet" />


<script src="~/Scripts/jquery-1.11.1.min.js"></script>
<script src="~/Scripts/jquery-2.1.3.js"></script>
<link href="~/Content/bootstrap.css" rel="stylesheet" />

<script src="~/Scripts/jquery-1.11.1.min.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/dataTables.js"></script>



<script type="text/javascript">
    $(function() {

    });

</script>

<br />
<br />

@if (TempData["Message"] != null)
{
    @Html.Partial("_Message", (Abundance_Rm.Model.Model.Message)TempData["Message"])
}


@using (Html.BeginForm("CreateFaculty", "Transcript", new { area = "admin" }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <br />
    <br />
    <br />

    <div class="panel panel-default">

        <div class="panel-body">

            <div class="row">

                <hr style="margin-top: 0" />
                <div class="col-md-12">

                    <div class="row">

                        <div class="col-md-6">
                            <div class="form-group">

                                @Html.LabelFor(model => model.Name, "Faculty Name", new { @class = "control-label " })
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "Business Administration" })
                                @Html.ValidationMessageFor(model => model.Name, null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">

                                @Html.LabelFor(model => model.FacultyCode, "Faculty Code", new { @class = "control-label " })
                                @Html.TextBoxFor(model => model.FacultyCode, new { @class = "form-control", @placeholder = " E.g Faculty code for Business Administration faculty can be BAM " })
                                @Html.ValidationMessageFor(model => model.FacultyCode, null, new { @class = "text-danger" })
                            </div>
                        </div>


                    </div>

                    <div class="row">
                        <div class="form-group">
                            <div class="col--2"></div>
                            <div class="col-sm-10">
                                <input class="btn btn-success mr5" type="submit" name="submit" value="Create" />

                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
}

Abundance_Rm/Areas/Admin/Views/Transcript/CreateSession.cshtml
@model Abundance_Rm.Model.Model.Session
@{
    ViewBag.Title = "Create Session";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br/>
<br/>
<div class="alert alert-success fade in nomargin">
    <h3 style="text-align: center">@ViewBag.Title</h3>

</div>


@if (TempData["Message"] != null)
{
    @Html.Partial("_Message", (Abundance_Rm.Model.Model.Message)TempData["Message"])
}

@using (Html.BeginForm("CreateSession", "Transcript", new { area = "admin" }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 style="-ms-align-content: center -webkit-align-content:center align-content:center">Student Result Upload</h3>
        </div>


        <div class="panel-body">

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">

                                @Html.LabelFor(model => model.Name, "Session", new {@class = "control-label "})
                                @Html.TextBoxFor(model => model.Name, new {@class = "form-control", @placeholder = "2017/2018", @required = true})
                                @Html.ValidationMessageFor(model => model.Name, null, new {@class = "text-danger"})
                            </div>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col-md-2">
                            <div class="form-group">

                                @Html.LabelFor(model => model.IsCurrenSession, "Activated", new {@class = "control-label "})
                                @Html.CheckBoxFor(model => model.IsCurrenSession, new {@class = "form-control col-md-1"})
                                @Html.ValidationMessageFor(model => model.IsCurrenSession, null, new {@class = "text-danger"})
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="form-group">
                            <div class="col--2"></div>
                            <div class="col-sm-10">
                                <input class="btn btn-success mr5" type="submit" name="submit" i value="Create"/>

                            </div>
                        </div>
                    </div>
                </div>

    </div>
}