Abundance_Rm/Areas/Student/ViewModels/ResultViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Abundance_Rm.Model.Model;
using Abundance_Rm.Models;

namespace Abundance_Rm.Areas.Student.ViewModels
{
    public class ResultViewModel
    {
        public ResultViewModel()
        {
            SessionSelectList = Utility.PopulateSessionListItem();
            SemesterSelectList = Utility.PopulateSemesterListItem();
        }
        public string MatricNumber { get; set; }
        public Semester Semester { get; set; }
        public Session Session { get; set; }
        public List<Result> Results { get; set; }
        public List<SelectListItem> SessionSelectList { get; set; }
        public List<SelectListItem> SemesterSelectList { get; set; }  

    }

    



}

Abundance_Rm/Areas/Student/Controllers/ResultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

using Abundance_Rm.Areas.Student.ViewModels;
using Abundance_Rm.Business;
using Abundance_Rm.Model.Model;
using Abundance_Rm.Model.Entity;
using Abundance_Rm.Controllers;
using System.Threading;

namespace Abundance_Rm.Areas.Student.Controllers
{
    [AllowAnonymous]
    public class ResultController : BaseController
    {
        private ResultViewModel viewModel;
        private StudentLogic studentLogic;

        public ResultController()
        {
            viewModel = new ResultViewModel();
            studentLogic = new StudentLogic();
        }

        //public ActionResult Check()
        //{
        //    viewModel = new ResultViewModel();
        //    ViewBag.Session = viewModel.SessionSelectList;
        //    ViewBag.Semester = viewModel.SemesterSelectList;
        //    return View();
        //}

        //[HttpPost]
        //public ActionResult Check(ResultViewModel vModel)
        //{
        //    try
        //    {
        //        if (vModel.Semester.Id > 0 && vModel.Session.Id > 0 && vModel.MatricNumber != null)
        //        {
        //            Model.Model.Student student = studentLogic.GetBy(vModel.MatricNumber);
        //            if (student != null && student.Id > 0)
        //            {
        //                StudentResultLogic studentResultLogic = new StudentResultLogic();
        //                StudentLevelLogic studentLevelLogic = new StudentLevelLogic();
        //                Semester semester = new Semester(){Id = vModel.Semester.Id};
        //                StudentLevel studentLevel = studentLevelLogic.GetModelBy(sl => sl.Person_Id == student.Id && sl.Session_Id == vModel.Session.Id);

        //                if (studentLevel != null)
        //                {
        //                    vModel.Results = studentResultLogic.GetSingleStudentResult(student, studentLevel.Session, semester, studentLevel.Level, studentLevel.Programme, studentLevel.Department);
        //                    vModel.StudentLevel = studentLevel;
        //                }
        //                else
        //                {
        //                    SetMessage("No Student Level Record!", Message.Category.Error);
        //                    ViewBag.Session = viewModel.SessionSelectList;
        //                    ViewBag.Semester = viewModel.SemesterSelectList;
        //                    return View("Check");
        //                }
                        
        //            }
        //            else
        //            {
        //                SetMessage("Invalid Matric Number!", Message.Category.Error);
        //                return RedirectToAction("Check");
        //            }
                    
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        SetMessage("Error Occurred! " + ex.Message, Message.Category.Error);
        //    }

        //    ViewBag.Session = viewModel.SessionSelectList;
        //    ViewBag.Semester = viewModel.SemesterSelectList;
        //    return View(vModel);
        //}
        public ActionResult Check()
        {
            try
            {
                viewModel = new ResultViewModel();
                ViewBag.Session = viewModel.SessionSelectList;
                ViewBag.Semester = viewModel.SemesterSelectList;
            }
            catch (Exception ex)
            {
               SetMessage("Error! " + ex.Message, Message.Category.Error); 
            }

            return View(viewModel);
        }
        [HttpPost]
        public ActionResult Check(ResultViewModel vModel)
        {
            try
            {
                if (vModel.Semester.Id > 0 && vModel.Session.Id > 0 && vModel.MatricNumber != null )
                {
                    Model.Model.Student student = studentLogic.GetBy(vModel.MatricNumber);
                    if (student != null && student.Id > 0)
                    {
                        Semester semester = new Semester() { Id = vModel.Semester.Id };
                        ;
                            return RedirectToAction("ViewResult",
                                new
                                {
                                    studentId = student.Id,
                                    sessionId = vModel.Session.Id,
                                    semesterId = semester.Id,
                                    levelId = student.CurrentLevel.Id,
                                    programmeId = student.Programme.ProgrammeType.Id,
                                    departmentId = student.Department.Id,
                                });
                    }
                    else
                    {
                        SetMessage("No Student found for this Matric Number!", Message.Category.Error);
                        ViewBag.Session = viewModel.SessionSelectList;
                        ViewBag.Semester = viewModel.SemesterSelectList;
                        return View("Check", viewModel);
                    }

                }
            }
            catch (Exception ex)
            {
                SetMessage("Error Occurred! " + ex.Message, Message.Category.Error);
            }

            ViewBag.Session = viewModel.SessionSelectList;
            ViewBag.Semester = viewModel.SemesterSelectList;
            return View(vModel);
        }

        public ActionResult ViewResult(long studentId, int sessionId, int semesterId, int levelId, int programmeId, int departmentId)
        {
            try
            {
                viewModel = new ResultViewModel();
                StudentCourseMarkLogic studentCourseMarkLogic = new StudentCourseMarkLogic();

                Model.Model.Session session = new Session() { Id = sessionId };
                Semester semester = new Semester() { Id = semesterId };
                Level level = new Level() { Id = levelId };
                ProgrammeType programme = new ProgrammeType() { Id = programmeId };
                Department department = new Department() { Id = departmentId };
                Model.Model.Student student = new Model.Model.Student() { Id = studentId };
                viewModel.Results = studentCourseMarkLogic.GetSingleStudentResult(student, session, semester, level, programme, department);
                
            }
            catch (Exception ex)
            {
                SetMessage("Error Occurred! " + ex.Message, Message.Category.Error);
            }

            return View(viewModel);
        }

     
        [AllowAnonymous]
        public ActionResult VerifyTranscript(string id)
        {
            if (!id.Contains('_'))
            {
                throw new ArgumentNullException("No Result Found Please Try Again");
            }
            ViewBag.StudentId = id;
            return View();
        }
    }
}

Abundance_Rm/Areas/Student/Views/Result/Check.cshtml
@model Abundance_Rm.Areas.Student.ViewModels.ResultViewModel
@{
    ViewBag.Title = "Semester Result";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<div class="row">

    <div class="col-md-12">
        <div class="col-md-1"></div>
        <div class="col-md-10">
                <div class="row">
                    <div class="col-md-12">
                        <h2>@ViewBag.Title</h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <section id="loginForm">
                            @using (Html.BeginForm("Check", "Result", new { Area = "Student" }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true)

                                <h5>Please enter your <b>Matric. No.</b> and select the appropriate fields below to check your result.</h5>
                                <hr class="no-top-padding" />

                                <div class="panel panel-default">
                                    <div class="panel-body">
                                         
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.MatricNumber, new { @class = "col-md-3 control-label" })
                                            <div class="col-md-9">
                                                @Html.TextBoxFor(m => m.MatricNumber, new { @class = "form-control", @required = "required" })
                                                @Html.ValidationMessageFor(m => m.MatricNumber, null, new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.Session.Name, "Session", new { @class = "control-label col-md-3" })
                                                <div class="col-md-6">
                                                    @Html.DropDownListFor(f => f.Session.Id, (IEnumerable<SelectListItem>)ViewBag.Session, new { @class = "form-control", @required = "required" })
                                                    @Html.ValidationMessageFor(model => model.Session.Id)
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.Semester.Name, "Semester", new { @class = "control-label col-md-3" })
                                                <div class="col-md-6">
                                                    @Html.DropDownListFor(f => f.Semester.Id, (IEnumerable<SelectListItem>)ViewBag.Semester, new { @class = "form-control", @required = "required" })
                                                    @Html.ValidationMessageFor(model => model.Semester.Id)
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-offset-3 col-md-9">
                                                <input type="submit" value="Check" class="btn btn-default" />
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="col-md-1"></div>
                                        <div class="col-md-10">
                                            @if (TempData["Message"] != null)
                                            {
                                                @Html.Partial("_Message", (Abundance_Rm.Model.Model.Message)TempData["Message"])
                                            }
                                        </div>
                                        <div class="col-md-1"></div>
                                    </div>
                                </div>
                            }
                        </section>
                    </div>
                </div>
            </div>
        <div class="col-md-1"></div>
            </div>
    </div>




        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

Abundance_Rm/Areas/Student/Views/Result/VerifyTranscript.cshtml
@{
    ViewBag.Title = "TranscriptReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script src="~/Scripts/jquery-1.10.2.min.js"></script>

    <script src="~/Scripts/responsive-tabs.js"></script>

    <script type="text/javascript">
               function resizeIframe(obj) {
            obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
        }
    </script>
}
  

<div style="color:black">
    <h3>
        Transcript Verification
    </h3>
</div>

<div class="alert alert-dismissible alert-success">
    <p>
        <b>Transcript Verification </b> displays an exportable and printable report of the student's results.
    </p>
</div>

<iframe src="@Url.Content("~/Report/Presenter/ResultTranscript.aspx?id=" + (string)ViewBag.StudentId)" style="width:100%; " frameborder="0" scrolling="no" id="iframe" onload='javascript:resizeIframe(this);'></iframe>


<br />

Abundance_Rm/Areas/Student/Views/Result/ViewResult.cshtml
@model Abundance_Rm.Areas.Student.ViewModels.ResultViewModel
@{
    ViewBag.Title = "ViewResult";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (Model.Results == null || Model.Results.Count == 0) { return; }
@if (Model != null && (Model.Results != null || Model.Results.Count > 0))
{
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                <div class="panel panel-default">
                    <div class="panel-body">

                        <div class="row">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Results[0].MatricNumber, "Matriculation Number : ", new { @class = "control-label" })
                                @Html.DisplayFor(model => model.Results[0].MatricNumber, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Results[0].ProgrammeTypeName, "Programme : ", new { @class = "control-label" })
                                @Html.DisplayFor(model => model.Results[0].ProgrammeTypeName, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Results[0].DepartmentName, "Department : ", new { @class = "control-label" })
                                @Html.DisplayFor(model => model.Results[0].DepartmentName, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Results[0].LevelName, "Level : ", new { @class = "control-label" })
                                @Html.DisplayFor(model => model.Results[0].LevelName, new { @class = "form-control" })
                            </div>
                        </div>

                        <table class="table table-responsive table-striped table-hover table-bordered">
                            <tr>
                                <th>COURSE</th>
                                <th>UNIT</th>
                                <th>GRADE</th>
                            </tr>
                            @for (int i = 0; i < Model.Results.Count; i++)
                            {
                                <tr>
                                    <td>
                                        @Model.Results[i].CourseCode.ToUpper()
                                    </td>
                                    <td>
                                        @Model.Results[i].CourseUnit
                                    </td>
                                    <td>
                                        @Model.Results[i].Grade
                                    </td>
                                </tr>
                            }
                        </table>

                        <br />
                        <div class="row">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Results.LastOrDefault().TotalSemesterCourseUnit, "Total Semester Course Unit : ", new { @class = "control-label" })
                                @Html.DisplayFor(model => model.Results.LastOrDefault().TotalSemesterCourseUnit, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Results.LastOrDefault().GPA, "GPA : ", new { @class = "control-label" })
                                @Html.DisplayFor(model => model.Results.LastOrDefault().GPA, new { @class = "form-control" })
                            </div>
                        </div>  
                        @if (Model.Results.LastOrDefault().CGPA != null)
                        {
                            <div class="row">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Results.LastOrDefault().CGPA, "CGPA : ", new { @class = "control-label" })
                                    @Html.DisplayFor(model => model.Results.LastOrDefault().CGPA, new { @class = "form-control" })
                                </div>
                            </div>
                        }
                        
                        <div class="row">
                            <div class="form-group">
                                @Html.DisplayFor(model => model.Results.LastOrDefault().Remark, new { @class = "form-control" })
                            </div>
                        </div>

                    </div>
                </div>

            </div>
            <div class="col-md-1"></div>
        </div>
    </div>
}