Abundance_Rm/Areas/Admin/Controllers/SessionController.cs
using Abundance_Rm.Areas.Admin.ViewModel;
using Abundance_Rm.Business;
using Abundance_Rm.Model.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Abundance_Rm.Areas.Admin.Controllers
{
    public class SessionController : Controller
    {
        private SessionLogic sessionLogic;
        private SessionViewModel sessionViewModel;
        private Session session;
        public SessionController()
        {
            sessionLogic = new SessionLogic();
            sessionViewModel = new SessionViewModel();
            session = new Session();
        }
        // GET: Admin/Session
        public ActionResult Index()
        {
            List<Session> sessionList = new List<Session>();
            sessionList = sessionLogic.GetAll().Where(p => p.IsRemoveRequested == false).ToList();
            sessionViewModel.SessionList = sessionList;
            return View(sessionViewModel);
        }

        public ActionResult AddSession(SessionViewModel viewModel)
        {
            try
            {
                var sessionselectlist = viewModel.SessionSectList.Where(p => p.Value == viewModel.SessionId.ToString()).SingleOrDefault().Text;   
                session.Name = sessionselectlist;
                session.IsRemoveRequested = false;
                session.Description = viewModel.Description;
                session.IsCurrenSession = viewModel.IsCurrenSession;
                sessionLogic.Create(session);
                TempData["msg"] = "Operation Successful";
            }
            catch (Exception)
            {
                TempData["msg"] = "Operation Failed";
            }
            return RedirectToAction("Index");
        }
    }
}

Abundance_Rm/Areas/Admin/Views/Session/Index.cshtml
@model Abundance_Rm.Areas.Admin.ViewModel.SessionViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br/>
@using (Html.BeginForm("AddSession","Session", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="panel panel-danger">
        <div class="panel panel-heading"><h3>Session</h3></div>
        <div class="panel-body">
            <div class="form-horizontal">
                @Html.Partial("_ErrorMessage")

                <div class="form-group">
                    @Html.LabelFor(model => model.SessionId, "Session Name", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.SessionId, Model.SessionSectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.SessionId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-danger" />
                    </div>
                </div>
            </div>

            @if (Model.SessionList != null)
            {
                <table class="table table-bordered table-striped table-condensed">
                    <tbody>
                        <tr>
                            <th>Session Name</th>
                            <th>Session Description</th>
                            <th></th>
                        </tr>
                    </tbody>
                    @foreach (var item in Model.SessionList)
                    {
                        <tbody>
                            <tr>
                                <td>@item.Name</td>
                                <td>@item.Description</td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { @id = item.SessionId }) |
                                    @Html.ActionLink("Delete", "Delete", new { @id = item.SessionId })
                                </td>

                            </tr>
                        </tbody>
                    }
                </table>

            }
        </div>
    </div>
    
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}